// _MainMenu_EOArchive.java
// Generated by EnterpriseObjects palette at Thursday, September 1, 2005 11:33:21 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MainMenu_EOArchive extends com.webobjects.eoapplication.EOArchive {
    ColorTile _colorTile0;
    GbaScreen _nsCustomView0;
    MainController _mainController0;
    PaletteController _paletteController0;
    TileGrid _nsCustomView1, _nsCustomView2;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1, _eoFrame2, _eoFrame3;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsColorWell0;
    javax.swing.JCheckBox _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7;
    javax.swing.JPanel _nsView0, _nsView1, _nsView2, _nsView3;

    public _MainMenu_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsColorWell0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2");
        _nsCustomView2 = (TileGrid)_registered(new TileGrid(), "View");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _paletteController0 = (PaletteController)_registered(new PaletteController(), "PaletteController");
        _colorTile0 = (ColorTile)_registered(new ColorTile(), "ColorTile");
        _nsCustomView1 = (TileGrid)_registered(new TileGrid(), "View");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _eoFrame3 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView3 = (JPanel)_eoFrame3.getContentPane();
        _nsButton7 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sprite Window"), "NSButton4112111");
        _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Window 1"), "NSButton411211");
        _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Window 0"), "NSButton41121");
        _nsButton4 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("BG 3"), "NSButton4112");
        _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("BG 2"), "NSButton4111");
        _nsButton2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sprite"), "NSButton411");
        _nsButton1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("BG 1"), "NSButton41");
        _nsButton0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("BG 0"), "NSButton4");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.layersWindow")) != null)) {
            _eoFrame2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame2");
        } else {
            _eoFrame2 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Layers");
        }

        _nsView2 = (JPanel)_eoFrame2.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.gbaWindow")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Main Window");
        }

        _nsView1 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.display")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (GbaScreen)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (GbaScreen)_registered(new GbaScreen(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate")) != null)) {
            _mainController0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (MainController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_mainController0");
        } else {
            _mainController0 = (MainController)_registered(new MainController(), "MainController");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.logView")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.logWindow")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Log");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "unhideAllApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hide", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hideOtherApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "orderFrontStandardAboutPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "terminate", ), ""));

        if (_replacedObjects.objectForKey("_mainController0") == null) {
            _connect(_owner(), _mainController0, "delegate");
        }
    }

    protected void _init() {
        super._init();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "arrangeInFront", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "clearRecentDocuments", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performZoom", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performClose", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "openDocument", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "showHelp", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performMiniaturize", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame3, "orderFront", ), ""));
        _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("HTML Value\n");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Value\n");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Address\n");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsCustomView2.setSize(192, 128);
        _nsCustomView2.setLocation(16, 11);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsCustomView2);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(224, 150);
        _nsBox3.setLocation(2, 15);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Sprites", true, "Lucida Grande", 11, Font.PLAIN));
        _connect(_nsCustomView1, _paletteController0, "target");
        _connect(_nsCustomView1, _paletteController0, "delegate");
        _connect(_paletteController0, _nsColorWell0, "colorWell");
        _connect(_nsCustomView2, _paletteController0, "target");
        _connect(_nsCustomView2, _paletteController0, "delegate");
        _connect(_nsCustomView2, _colorTile0, "standardTile");
        _connect(_paletteController0, _nsCustomView2, "spriteGrid");
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(true);
        _nsTextField2.setOpaque(true);
        _nsTextField2.setText("");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(true);
        _nsTextField2.setEnabled(true);
        _connect(_paletteController0, _nsTextField2, "html");
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(true);
        _nsTextField1.setOpaque(true);
        _nsTextField1.setText("");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(true);
        _nsTextField1.setEnabled(true);
        _connect(_paletteController0, _nsTextField1, "value");
        _connect(_paletteController0, _nsCustomView1, "bgGrid");
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(true);
        _nsTextField0.setOpaque(true);
        _nsTextField0.setText("");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(true);
        _nsTextField0.setEnabled(true);
        _connect(_paletteController0, _nsTextField0, "address");
        _connect(_paletteController0, _colorTile0, "tile");
        _connect(_nsCustomView1, _colorTile0, "standardTile");
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsCustomView1.setSize(192, 128);
        _nsCustomView1.setLocation(16, 11);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsCustomView1);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(224, 150);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Background", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(228, 167);
        _nsBox0.setLocation(-4, -4);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsBox0);
        _nsBox2.setSize(228, 167);
        _nsBox2.setLocation(-4, 167);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsBox2);
        _nsColorWell0.setSize(52, 52);
        _nsColorWell0.setLocation(288, 60);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsColorWell0, EOViewLayout.MinYMargin);
        _nsView3.add(_nsColorWell0);
        _nsTextField0.setSize(90, 22);
        _nsTextField0.setLocation(270, 145);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField0);
        _nsTextField3.setSize(114, 17);
        _nsTextField3.setLocation(258, 127);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField3);
        _nsTextField1.setSize(58, 22);
        _nsTextField1.setLocation(286, 195);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField1);
        _nsTextField4.setSize(114, 17);
        _nsTextField4.setLocation(258, 177);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField4);
        _nsTextField2.setSize(66, 22);
        _nsTextField2.setLocation(282, 243);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField2);
        _nsTextField5.setSize(114, 17);
        _nsTextField5.setLocation(258, 225);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField5);
        _nsView3.setSize(398, 330);
        _eoFrame3.setTitle("Palettes");
        _eoFrame3.setLocation(513, 251);
        _eoFrame3.setSize(398, 330);
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame0, "orderFront", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "connectToGdb", ), ""));

        if (_replacedObjects.objectForKey("_mainController0") == null) {
            _connect(_mainController0, _eoFrame0, "logWindow");
        }

        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame2, "orderFront", ), ""));
        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton7), ""));
        _setFontForComponent(_nsButton7, "Lucida Grande", 13, Font.PLAIN);
        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton6), ""));
        _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton5), ""));
        _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton4), ""));
        _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton3), ""));
        _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton2), ""));
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton1), ""));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_mainController0, "toggleLayer", _nsButton0), ""));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(63, 17);
        _nsButton0.setLocation(-3, -1);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton0);
        _nsButton1.setSize(63, 17);
        _nsButton1.setLocation(-3, 19);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton1);
        _nsButton2.setSize(63, 17);
        _nsButton2.setLocation(-3, 79);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton2);
        _nsButton3.setSize(63, 17);
        _nsButton3.setLocation(-3, 39);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton3);
        _nsButton4.setSize(63, 17);
        _nsButton4.setLocation(-3, 59);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton4);
        _nsButton5.setSize(97, 17);
        _nsButton5.setLocation(-3, 99);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton5);
        _nsButton6.setSize(97, 17);
        _nsButton6.setLocation(-3, 119);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton6);
        _nsButton7.setSize(112, 17);
        _nsButton7.setLocation(-3, 139);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton7);

        if (_replacedObjects.objectForKey("_eoFrame2") == null) {
            _nsView2.setSize(105, 154);
            _eoFrame2.setTitle("Layers");
            _eoFrame2.setLocation(136, 430);
            _eoFrame2.setSize(105, 154);
        }

        if (_replacedObjects.objectForKey("_mainController0") == null) {
            _connect(_mainController0, _eoFrame2, "layersWindow");
        }

        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsCustomView0.setSize(240, 160);
        _nsCustomView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView1.setSize(226, 148);
            _eoFrame1.setTitle("VBA Step");
            _eoFrame1.setLocation(262, 432);
            _eoFrame1.setSize(226, 148);
        }

        if (_replacedObjects.objectForKey("_mainController0") == null) {
            _connect(_mainController0, _eoFrame1, "gbaWindow");
        }

        if (_replacedObjects.objectForKey("_mainController0") == null) {
            _connect(_mainController0, _nsCustomView0, "display");
        }

        if (_replacedObjects.objectForKey("_mainController0") == null) {
            _connect(_mainController0, _nsTextView0, "logView");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(false);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("");
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextView0.setSize(369, 153);
        _nsTextView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(355, 141);
            _eoFrame0.setTitle("Log");
            _eoFrame0.setLocation(135, 250);
            _eoFrame0.setSize(355, 141);
        }
    }
}
